name: Build Checks
on: [push]

jobs:
  checks:
    strategy:
      matrix:
        version: ["13.5", "14.4", "15.0"]
    runs-on: ubuntu-latest
    name: Continuous Integration
    env:
      BATCH: true
    steps:
    - uses: actions/checkout@v4
    - name: "FreeBSD ${{ matrix.version }}"
      id: port_checks
      uses: vmactions/freebsd-vm@v1
      with:
        release: "${{ matrix.version }}"
        usesh: true
        envs: BATCH
        cpu: 1
        arch: x86_64
        mem: 1024
        prepare: |
          pkg install -q -y gitup portconfig
          pkg install -q -y gtar patchelf squashfs-tools-ng grub2-bhyve socat
          gitup ports -v0

          kldload linux64
          mkdir -p /compat/linux

          mkdir -p /wrkdirs
          chown -R nobody:nogroup /wrkdirs
          echo "WRKDIRPREFIX=/wrkdirs" >> /etc/make.conf

        run: |
          set -exu

          for port in net/wifibox-alpine net/wifibox-core net/wifibox; do
            make -C "$port" checksum
            su -m nobody -c "make -C $port"
            su -m nobody -c "make -C $port check-plist"
            make -C "$port" install
            su -m nobody -c "make -C $port clean"
          done

          make -C net/wifibox deinstall
          make -C net/wifibox-core deinstall
          make -C net/wifibox-alpine deinstall
